apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oms.pubsub
  namespace: oms
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.redis.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-password
      key: redis-password
scopes:
  - order-service
  - order-processor-service
  - make-line-service

  