apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oms.state.all
  namespace: order-system
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: valkey.redis.svc.cluster.local:6379
