apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oms.pubsub
  namespace: oms
spec:
  type: pubsub.kafka
  version: v1  
  metadata:
  - name: brokers
    value: kafka.kafka.svc.cluster.local:9092
  - name: authType
    value: "password"
  - name: saslUsername
    value: "user1"
  - name: saslPassword
    value: 6PwH3IHkUF #Update me!
  - name: disableTls 
    value: "true"
scopes:
  - order-service
  - order-processor-workflow
  - make-line-service