# apiVersion: dapr.io/v1alpha1
# kind: Subscription
# metadata:
#   name: oms.subscription.orders
#   namespace: oms
# spec:
#   topic: orders
#   route: /orders
#   pubsubname: oms.pubsub
# scopes:
# - order-processor-workflow
