@makeline-service = 127.0.0.1:5200
@storeId = Seattle

### Get all orders waiting to be made via makeline-service
GET http://{{makeline-service}}/orders/{{storeId}}

### HEalth check
GET http://{{makeline-service}}/ready

//GET http://127.0.0.1:5580/v1.0/invoke/make-line-service/method/orders/{{storeId}}

GET http://0.0.0.0:5180/v1.0/invoke/order-service/method/orders/{{storeId}}


### Complete (delete) an order via makeline-service (NOTE: replace the GUID with an actual orderId)
DELETE http://{{makeline-service}}/orders/{{storeId}}/b32f3d57-277a-40b0-a2f0-0ab2f056d654
