@makeline-service = 127.0.0.1:5200
@storeId = Seattle

### Get all orders waiting to be made via makeline-service
GET http://{{makeline-service}}/orders/{{storeId}}

### HEalth check
GET http://{{makeline-service}}/ready

//GET http://127.0.0.1:5580/v1.0/invoke/make-line-service/method/orders/{{storeId}}

GET http://0.0.0.0:5180/v1.0/invoke/order-service/method/orders/{{storeId}}


### Complete (delete) an order via makeline-service (NOTE: replace the GUID with an actual orderId)
DELETE http://{{makeline-service}}/orders/{{storeId}}/df775eeb-fd6c-4c81-8ed5-4d0f579ddd86
