@daprHttp=http://104.196.236.53:8085

### Get Dapr actor info
GET {{ daprHttp }}/dapr/config
dapr-app-id: worker-actor

### Test Worker

GET {{ daprHttp }}/v1.0/actors/Worker/1/method/CompleterOrder
dapr-app-id: worker-actor
Content-Type: application/json

"7778888999"
