apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: oms.pubsub
  namespace: oms
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
scopes:
  - order-service
  - order-processor-service
  