apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: oms.subscription.ordercompleted
  namespace: oms
spec:
  topic: ordercompleted
  route: /ordercompleted
  pubsubname: oms.pubsub
scopes:
- order-processor-workflow