apiVersion: apps/v1
kind: Deployment
metadata:
  name: make-line-service
  namespace: order-system
  labels:
    app: make-line-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: make-line-service
  template:
    metadata:
      labels:
        app: make-line-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "make-line-service"
        dapr.io/app-port: "80"
        dapr.io/config: "config"
        # dapr.io/http-max-request-size: "16"
    spec:
      containers:
        - name: make-line-service
          image: "us-central1-docker.pkg.dev/prj-common-d-shared-89549/reg-d-common-docker-public/order-system/make-line-service:latest"
          env:
          - name: APP_PORT
            value: "80"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 6
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 12
            periodSeconds: 10