apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-customer
  namespace: order-system
  labels:
    app: virtual-customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: virtual-customer
  template:
    metadata:
      labels:
        app: virtual-customer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "virtual-customer"
        dapr.io/config: "config"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name: virtual-customer
          image: "rochabr/virtual-customer:0.7.4"
          imagePullPolicy: Always
          env:
          - name: STORE_ID
            value: "Seattle"
          - name: MAX_ITEM_QUANTITY
            value: "2"
          - name: MIN_SEC_TO_PLACE_ORDER
            value: "7"
          - name: MAX_SEC_TO_PLACE_ORDER
            value: "15"
          - name: MIN_SEC_BETWEEN_ORDERS
            value: "5"
          - name: MAX_SEC_BETWEEN_ORDERS
            value: "10"
          - name: NUM_ORDERS
            value: "300"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1"