apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-worker
  namespace: order-system
  labels:
    app: virtual-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-worker
  template:
    metadata:
      labels:
        app: virtual-worker
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "virtual-worker"
        dapr.io/app-port: "80"
        dapr.io/config: "config"
    spec:
      containers:
        - name: virtual-worker
          image: "us-central1-docker.pkg.dev/prj-common-d-shared-89549/reg-d-common-docker-public/order-system/virtual-worker:0.6.0"
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            failureThreshold: 6
            periodSeconds: 10
          env:
          - name: APP_PORT
            value: "80"
          - name: STORE_ID
            value: "Seattle"
          - name: MIN_SECONDS_TO_COMPLETE_ITEM
            value: "5"
          - name: MAX_SECONDS_TO_COMPLETE_ITEM
            value: "12"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1"