name: Build and Push Loyalty Service Image

on:
  push:
    branches:
      - demo-scenarios
    paths:
      - 'go/loyalty-service/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'    
    environment: development
    env:
      GCP_PROJECT_ID: '${{ secrets.GCP_PROJECT_ID }}'
      GCP_DOCKER_REPOSITORY: '${{ secrets.GCP_DOCKER_REPOSITORY }}'
      GCP_CONTAINER_REGISTRY_HOST: '${{ secrets.GCP_CONTAINER_REGISTRY_HOST }}'
      IMAGE_NAME: order-system/loyalty-service

      GKE_CLUSTER: gke_prj-dataplane-n-demo-30534_us-west1-a_gke-n-dataplane-demo-us-west1-a2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: Configure Google Credentials
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{ secrets.SERVICE_ACCOUNT}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Auth
        uses: 'docker/login-action@v3'
        with:
          registry: '${{ env.GCP_CONTAINER_REGISTRY_HOST }}'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          
      - name: Build and Push Docker Image (AMD, ARM)
        working-directory: go/$SERVICE_NAME
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $GCP_CONTAINER_REGISTRY_HOST/$GCP_PROJECT_ID/$GCP_DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_SHA . --push
    
  deploy-to-enteprise_cluster:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'    
    environment: demo
    env:
      GCP_PROJECT_ID: '${{ vars.GCP_DP_PROJECT_ID }}'
      IMAGE_NAME: order-system/loyalty-service
      SERVICE_NAME: loyalty-service
      GKE_CLUSTER: '${{ vars.GCP_DP_GKE_CLUSTER_NAME_2 }}'
      GKE_ZONE: '${{ vars.GCP_DP_GKE_ZONE }}'
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: Configure Google Credentials
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT}}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: 'gke-gcloud-auth-plugin'
    
      # Set up kustomize
      - name: Set up Kustomize
        working-directory: ./deployment-files/
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Replace the target image name in the kustomization.yaml
        run: |
          kustomize edit add resource ./k8s/$SERVICE_NAME.yaml && kustomize edit set image $IMAGE_NAME:tag=us-central1-docker.pkg.dev/prj-common-d-shared-89549/reg-d-common-docker-public/$IMAGE_NAME:$GITHUB_SHA
        working-directory: ./deployment-files/

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -k ./deployment-files/


  deploy-to-free-tier-cluster:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'    
    environment: demo
    env:
      GCP_PROJECT_ID: '${{ vars.GCP_DP_PROJECT_ID }}'
      IMAGE_NAME: order-system/loyalty-service
      SERVICE_NAME: loyalty-service
      GKE_CLUSTER: '${{ vars.GCP_DP_GKE_CLUSTER_NAME_1 }}'
      GKE_ZONE: '${{ vars.GCP_DP_GKE_ZONE }}'
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: Configure Google Credentials
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT}}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: 'gke-gcloud-auth-plugin'
    
      # Set up kustomize
      - name: Set up Kustomize
        working-directory: ./deployment-files/
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Replace the target image name in the kustomization.yaml
        run: |
          kustomize edit add resource ./k8s/$SERVICE_NAME.yaml && kustomize edit set image $IMAGE_NAME:tag=us-central1-docker.pkg.dev/prj-common-d-shared-89549/reg-d-common-docker-public/$IMAGE_NAME:$GITHUB_SHA
        working-directory: ./deployment-files/

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl apply -k ./deployment-files/
  